---

- name: create /var/www/{.composer,beanstalk}
  file: dest=/var/www/{{item}}
    state=directory
    owner=www-data
    group=www-data
    mode=0750
  with_items:
    - beanstalk
    - .composer

- name: install beanstalk-console
  command: composer create-project ptrofimov/beanstalk_console /var/www/beanstalk/
    chdir=/var/www/beanstalk/
    creates=/var/www/beanstalk/public
  sudo_user: www-data

- name: install beanstalk config file
  template: src=config.php
    dest=/var/www/beanstalk/config.php
    owner=www-data
    group=www-data
    mode=0440

- name: install apache template
  template: src=apache/beanstalk.conf
    dest=/etc/apache2/conf-available/beantalk.conf
  notify: reload apache2

- name: enable apache template
  command: a2enconf beanstalk.conf
    creates=/etc/apache2/conf-enabled/beanstalk.conf
  notify: reload apache2
